# versionは、3系
version: "3"
# Serviceを設定する
services:
  # Service名は、自由に決めていい
  frontend:
    # DockerfileまでのPath
    build: .
    # ホストマシン:コンテナ => ファイルを共有するための設定
    volumes:
      - ./app:/usr/src/app
    # ホストマシンPort番号:コンテナのPost番号
    ports:
      - 3001:3000
    # CLI画面の操作をできるようにする
    tty: true
